### ISSUE TITLE
Python2 -->Python3 ConfigParser and related errors

### ISSUE THREAD

**Issue by nbanik** [ruggiero/galstep#2]
Hi Rafael, 

   I am trying to use galstep to generate isolated disk galaxies with a gas disk, but I am running into some trouble, which I think are stemming from me modifying the ConfigParser --> configparser in the code to be compatible with python3, I changed from ConfigParser import ConfigParser --> from configparser import ConfigParser
I ran the code using : python galstep.py -i params_galaxy.ini -o test.dat --hdf5 --force-no -cores 1 and 

Here is the output : 

Setting positions...
10% of halo mass cut by the truncation...
0% of disk mass cut by the truncation...
9% of bulge mass cut by the truncation...
0% of disk mass cut by the truncation...
Building gravity tree...
Filling potential grid...ous disk
Process Process-1:1
Setting temperatures...
Setting densitites...
Setting velocities...
galstep.py:232: RuntimeWarning: overflow encountered in cosh
  return cte * (1/cosh(z/z0))**2 * exp(-rho/Rd)
galstep.py:400: RuntimeWarning: overflow encountered in double_scalars
  sz_grid[1][i][j] = (1/disk_density(rho_axis[i], z_axis[j], M_disk, z0) *
galstep.py:401: RuntimeWarning: invalid value encountered in double_scalars
  integrate.simps(ys[1][i][j:], z_axis[j:]))
galstep.py:400: RuntimeWarning: divide by zero encountered in double_scalars
  sz_grid[1][i][j] = (1/disk_density(rho_axis[i], z_axis[j], M_disk, z0) *
galstep.py:418: RuntimeWarning: divide by zero encountered in double_scalars
  gamma2 = 4/(kappa2*rho_axis[i]) * dphi/drho
galstep.py:418: RuntimeWarning: invalid value encountered in double_scalars
  gamma2 = 4/(kappa2*rho_axis[i]) * dphi/drho
Traceback (most recent call last):
  File "galstep.py", line 570, in <module>
    main()
  File "galstep.py", line 33, in main
    write_input_file(galaxy_data)
  File "galstep.py", line 550, in write_input_file
    file_format=file_format)
  File "/scratch/user/banik/galstep/galstep/snapwrite.py", line 85, in write_snapshot
    header_data, raw_hdata = read_header(folder, n_part, input_)
  File "/scratch/user/banik/galstep/galstep/snapwrite.py", line 30, in read_header
    h_data.append(config.getint('header', 'flag_metals'))
  File "/scratch/user/banik/.conda/envs/galpy1.7/lib/python3.7/configparser.py", line 818, in getint
    fallback=fallback, **kwargs)
  File "/scratch/user/banik/.conda/envs/galpy1.7/lib/python3.7/configparser.py", line 808, in _get_conv
    **kwargs)
  File "/scratch/user/banik/.conda/envs/galpy1.7/lib/python3.7/configparser.py", line 802, in _get
    return conv(self.get(section, option, **kwargs))
ValueError: invalid literal for int() with base 10: '0 ;'

**Comment by regmachado** [comment]
Here's a new version of galstep, ported to python3:

[https://github.com/elvismello/galstep](https://github.com/elvismello/galstep)

If there are problems, please let us know.
